[package]
name = "lmdb-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lmdb = "0.8.0"


serde = { version = "1.0.163", features = ["derive"] }
serde-pickle = "1.1.1"
tempdir = "0.3.7"
